LOCAL_PATH := $(call my-dir)

#OOS Ported Screen Recorder
include $(CLEAR_VARS)
LOCAL_MODULE := ScreenRecorder
LOCAL_SRC_FILES := priv-app/ScreenRecorder.apk
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app/
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
